### ISSUE TITLE
help files - page title

### ISSUE THREAD

**Issue by frase-git** [cmb69/polyglott_xh#24]
The help files have as page title (in tab) "Slideshow_XH".

That's what you get when you use "pandoc" ;-)

**Comment by cmb69** [comment]
I'd rather blame copy-pasta: https://github.com/cmb69/polyglot_xh/blob/243ea4f543f5bc529c2efd13e3cf22a5e0fe9002/help/template.htm#L7

Anyhow, thanks for reporting!

**Comment by frase-git** [comment]
I only came up with "pandoc" because there is also a file "template.htm" lying around - and it says something about "pandoc".

**Comment by cmb69** [comment]
Yeah, pandoc is used to generate help.htm from README.md using template.htm. The problem is that template.htm is *almost* identical for my plugins, so I copy & paste it; in this case I forgot to adjust the title. I should probably move the plugin name to the build command line instead of having to adjust in template.htm.
